export const DB_PROVIDER = 'DATABASE_CONNECTION_TOKEN';
export const RESTAURANT_MODEL_PROVIDER = 'RESTAURANT_MODEL_TOKEN';
export const USER_MODEL_PROVIDER = 'USER_MODEL_TOKEN';
export const CONFLICT_ERROR_CODE = 11000;